### ISSUE TITLE
_msbt can't be imported

### ISSUE THREAD

**Issue by fellobo** [pybluez/pybluez#104]
I am using Python 2.7 and have installed pybluez (no problem,) and when I run my code that has import bluetooth I get the following error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.0\visualstudio_py_util.py", line 76, in exec_file
    exec(code_obj, global_variables)
  File "....\bt.py", line 3, in <module>
    import bluetooth
  File "C:\Python27\lib\site-packages\bluetooth__init__.py", line 37, in <module>
    from .msbt import *
  File "C:\Python27\lib\site-packages\bluetooth\msbt.py", line 2, in <module>
    import bluetooth._msbt as bt
ImportError: No module named _msbt
Press any key to continue . . .

I have been searching for the _msbt to see what package I need to get that pulled in but am having no luck.

**Comment by fellobo** [comment]
You know what; I fixed it.  I think when I was trying to install the PyBluez it didn't fully work for me.  It kept telling me I was running PyBluez (0.21) Which was odd because I thought I installed 0.22.  Anyway, I uninstalled PyBluez 0.21 (or deleted a temp location that pip said it would delete) and tried installing the PyBluez 0.22 and it worked.  Then my code worked.  

I am leaving this here just in case someone else sees the same issue.
