### ISSUE TITLE
ubuntu 16.04LTS / pybluez ble not working any more

### ISSUE THREAD

**Issue by mstekker** [pybluez/pybluez#125]
Hello,

Installation of pybluez ble under ubuntu 16.04LTS is broken. After:

pip install pybluez[ble]

the following error occurs:
`pip install pybluez[ble]
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 270, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 234, in from_line
    extras).extras
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'__placeh'"
`

Someone has any ideas?

Mart

**Comment by karulis** [comment]
Updating pip helped:
pip3 install -U pip
pip install -U pip

Please reopen if it does not help
