### ISSUE TITLE
Mac OS rfcomm_client find_service error 

### ISSUE THREAD

**Issue by Nishanksingla** [pybluez/pybluez#128]
I am trying to connect raspberry Pi with Macbook OSX 10.11 via bluetooth.
rfcomm-server.py is running on raspberry Pi successfully. 

rfcomm-client.py is giving me following error on Mac OSX

Traceback (most recent call last):
  File "rfcomm-client.py", line 9, in <module>
    service_matches = find_service( uuid = uuid, address = addr )
  File "build/bdist.macosx-10.11-intel/egg/bluetooth/osx.py", line 49, in find_service
  File "build/bdist.macosx-10.11-intel/egg/lightblue/_lightblue.py", line 103, in findservices
  File "build/bdist.macosx-10.11-intel/egg/lightblue/_lightblue.py", line 529, in _getservicetuple
TypeError: Need 1 arguments, got 0

Please help me in resolving this issue.

**Comment by karulis** [comment]
I believe this is same issue as #102
