### ISSUE TITLE
[Errno 97] Address family not supported by protocol on Python 3.5+

### ISSUE THREAD

**Issue by philhawthorne** [pybluez/pybluez#139]
Discovered this while using [Home Assistant](http://home-assistant.io).

There is an issue affecting Bluetooth discovery with Python 3.5 and 3.6. More information here: https://bugs.python.org/issue27929

In Home Assistant the following stack trace is raised

```
homeassistant.components.device_tracker: Error setting up platform bluetooth_tracker
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/device_tracker/__init__.py", line 148, in setup_platform
    if not platform.setup_scanner(hass, p_config, tracker.see):
  File "/usr/src/app/homeassistant/components/device_tracker/bluetooth_tracker.py", line 61, in setup_scanner
    for dev in discover_devices():
  File "/usr/src/app/homeassistant/components/device_tracker/bluetooth_tracker.py", line 39, in discover_devices
    lookup_class=False)
  File "/config/deps/bluetooth/bluez.py", line 26, in discover_devices
    device_id = _bt.hci_get_route()
OSError: [Errno 97] Address family not supported by protocol
```

Not sure if there is a fix this library can put in? Or if we'll just have to wait for a new Python fix.

Original Home Assistant issue: home-assistant/home-assistant#3838

**Comment by karulis** [comment]
I believe it is better to wait for fix,then implement workarounds
Thank You for reporting

**Comment by bruno-cassina** [comment]
any solutions????
```
Traceback (most recent call last):
  File "/mnt/c/Users/hotpe/Desktop/apple_bleee/ble_read_state.py", line 65, in <module>
    toggle_device(dev_id, True)
  File "/mnt/c/Users/hotpe/Desktop/apple_bleee/utils/bluetooth_utils.py", line 88, in toggle_device
    hci_sock = socket.socket(socket.AF_BLUETOOTH,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```
