### ISSUE TITLE
Issue importing bluetooth on OSX 

### ISSUE THREAD

**Issue by mhassell** [pybluez/pybluez#144]
Good evening,  I just installed pybluez and attempt to run import bluetooth in a python shell, I get the following errors:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/bluetooth/__init__.py", line 47, in <module>
  File "build/bdist.macosx-10.11-intel/egg/bluetooth/osx.py", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/lightblue/__init__.py", line 160, in <module>
  File "build/bdist.macosx-10.11-intel/egg/lightblue/_lightblue.py", line 31, in <module>
  File "build/bdist.macosx-10.11-intel/egg/lightblue/_macutil.py", line 169, in <module>
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector sleep of BBCocoaSleeper at 0x111c68100>

If I persist and try importing again, I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/bluetooth/__init__.py", line 47, in <module>
  File "build/bdist.macosx-10.11-intel/egg/bluetooth/osx.py", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/lightblue/__init__.py", line 160, in <module>
  File "build/bdist.macosx-10.11-intel/egg/lightblue/_lightblue.py", line 28, in <module>
ImportError: cannot import name _IOBluetooth

Any advice would be appreciated.

**Comment by mhassell** [comment]
Sorry, realized that this isn't compatible with OSX.

**Comment by rgov** [comment]
@mhassell It should be more compatible with macOS now, if you want to try.
