### ISSUE TITLE
Unable to pip install  on windows 10

### ISSUE THREAD

**Issue by ofaurax** [pybluez/pybluez#147]
From the windows command line (tested also with powershell), I'm unable to install latest pybluez (0.22) using pip.

Here is the log:
```
C:\Python3>pip --version
pip 9.0.1 from c:\python3\lib\site-packages (python 3.6)

C:\Python3>pip install pybluez
Collecting pybluez
  Using cached PyBluez-0.22.zip
Installing collected packages: pybluez
  Running setup.py install for pybluez ... error
Exception:
Traceback (most recent call last):
  File "c:\python3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 37: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 37: invalid start byte

```

**Comment by potofpie** [comment]
I had a similar problem on linux. I have both python 3 and to installed on my computer and I used python 2 and it worked. I would try to find some software that easily let's you switch be between but I'm positive switch to python 2 will fix this problem.
