### ISSUE TITLE
OS X issue while import: 'module' object has no attribtue 'setSignatureForSelector'

### ISSUE THREAD

**Issue by rdednl** [pybluez/pybluez#168]
```
>>> import bluetooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/bluetooth/__init__.py", line 47, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/bluetooth/osx.py", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lightblue/__init__.py", line 160, in <module>
    from _lightblue import *
  File "/usr/local/lib/python2.7/site-packages/lightblue/_lightblue.py", line 27, in <module>
    import _IOBluetooth
  File "/usr/local/lib/python2.7/site-packages/lightblue/_IOBluetooth.py", line 61, in <module>
    objc.setSignatureForSelector("IOBluetoothSDPServiceRecord",
AttributeError: 'module' object has no attribute 'setSignatureForSelector'
>>>
```

issue while importing in python2.7 on mac os x sierra 10.12.6.

**Comment by rgov** [comment]
macOS support should be improved now, please try again with the latest version on GitHub. (It has not yet been released to PyPI.)
