### ISSUE TITLE
Problème connexion (Bind Port) with windows 10

### ISSUE THREAD

**Issue by yassinemour** [pybluez/pybluez#206]
## System

 - **Operating System: Windows 10
 - **Hardware:** ( external Bluetooth adaptor
 - **PyBluez Version:** Python 2.7 ==> git+https://github.com/karulis/pybluez.git@35296f4246e084928292fd22a232f06307711564

## Issue

Hello,

I try to connect my tablet with a smart phone (Bluetooth connexion) using an application developed by Python and using pybluez, but i have this error: 
//////////////////////////////////////
**2018-08-06 05:34:10,584 INFO    root                 | Bluetooth service: UP
2018-08-06 05:34:10,584 DEBUG   digit.bt.service     | listen: bind to port 1
2018-08-06 05:34:10,849 DEBUG   digit.bt.service     | listen: bind to port **1**
2018-08-06 05:34:11,115 DEBUG   digit.bt.service     | listen: bind to port 1
2018-08-06 05:34:11,381 DEBUG   digit.bt.service     | listen: bind to port 1
2018-08-06 05:34:11,647 DEBUG   digit.bt.service     | listen: bind to port 1
2018-08-06 05:34:11,647 DEBUG   digit.bt.service     | listen: server_sock closed in finally block
2018-08-06 05:34:11,647 ERROR   digit.bt.service     | RetryError[Attempts: 5, Error:
  File "retrying.py", line 200, in call
  File "digit/bt/service.py", line 90, in bind_socket
  File "bluetooth/msbt.py", line 66, in bind
]
Traceback (most recent call last):
  File "digit/bt/service.py", line 70, in run
  File "digit/bt/service.py", line 94, in listen
  File "retrying.py", line 49, in wrapped_f
  File "retrying.py", line 214, in call
RetryError: RetryError[Attempts: 5, Error:
  File "retrying.py", line 200, in call
  File "digit/bt/service.py", line 90, in bind_socket
  File "bluetooth/msbt.py", line 66, in bind
]
2018-08-06 05:34:11,647 INFO    root                 | **bye****
///////////////////////////////////////////////////////////////////////////
I have this error just in windows 10, the connexion work normaly in windows 7 and XP.
Also in windows 10 sometimes works and somtimes doesn't work.

Could you please Help me?
Thanks in davance.

**Comment by rgov** [comment]
Could you please make a reduced test case that exemplifies the problem?
