### ISSUE TITLE
encoding errors with python3

### ISSUE THREAD

**Issue by laurentsenta** [pybluez/pybluez#322]
## System

 - **Operating System:** raspbian <-> macos
 - **Hardware:**  raspberry pi zero w <-> mac
 - **Python Version:** 3.7
 - **PyBluez Version:** 0.23

## Issue

First of all, thanks for taking care of this library!

I used the examples to start a server on a raspberry pi and use SPD to connect to the server from macOS. I see a lot of encoding problems on the macOS client:

```
Traceback (most recent call last):
  File "client.py", line 19, in <module>
    uuid=uuid)
  File "/Users/laurent/.virtualenvs/focus/lib/python3.7/site-packages/bluetooth/macos.py", line 49, in find_service
    dresults = lightblue.findservices(addr=address, name=name)
  File "/Users/laurent/.virtualenvs/focus/lib/python3.7/site-packages/lightblue/_lightblue.py", line 76, in findservices
    "failed to find " + devaddr
TypeError: can only concatenate str (not "bytes") to str
```

fixed by using `devaddr.decode()` in `_lightblue.py` line 76

Then:

```
Traceback (most recent call last):
  File "client.py", line 18, in <module>
    services = find_service(uuid=uuid)
  File "/Users/laurent/.virtualenvs/focus/lib/python3.7/site-packages/bluetooth/macos.py", line 49, in find_service
    dresults = lightblue.findservices(addr=address, name=name)
  File "/Users/laurent/.virtualenvs/focus/lib/python3.7/site-packages/lightblue/_lightblue.py", line 77, in findservices
    raise _lightbluecommon.BluetoothError(msg)
lightblue._lightbluecommon.BluetoothError: findservices() failed, failed to find 34:XX:XX:XX:XX
```

fixed by using `address.decode()` in `macos.py` line 49.

**Comment by rgov** [comment]
Would you mind sending a pull request with those changes?
