### ISSUE TITLE
Weird OSError in Windows 10 when calling recv

### ISSUE THREAD

**Issue by franklevasseur** [pybluez/pybluez#324]
## System

 - **Operating System:** Windows 10
 - **Hardware:** Dell xps 15
 - **Python Version:** 3.7.3
 - **PyBluez Version:** 0.22 (I'm actually using the PyBluez-Win10 package version 0.22)

## Issue

A super weird OSError was thrown when calling ```client_sock.recv(1024)```

My program works fine on linux (Ubuntu 18.04) and it used to work fine on windows, but recently it started crashing...

The exception instance has no ```errno``` field or any information at all.

While debugging I mannaged to put my hand on the stack trace (which was contained in some field of the exception instance):

```
Traceback (most recent call last):
  File "./backend\\bluetooth_service.py", line 114, in read_bytes
  data = self.client_sock.recv(1024)
  File "C:\\Users\\franc\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\bluetooth\\msbt.py", line 102, in recv

    return bt.recv (self._sockfd, numbytes)
	OSError
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	File "c:\\Users\\franc\\.vscode\\extensions\\ms-python.python-2020.3.69010\\pythonFiles\\lib\\python\\debugpy\\wheels\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_resolver.py", line 215, in _get_py_dictionary
    attr = getattr(var, name)
	AttributeError: characters_written
```

My code is located [here](https://github.com/franklevasseur/ossicles-server/blob/b48258f1a39eb998e48353745f6b6eae24d7d9b5/backend/bluetooth_service.py#L108).

Any help would be appreciated!

I really need to make my app cross plateform...

Thank you in advance and sorry for my bad english,

François

**Comment by franklevasseur** [comment]
Ok, after further investigations, it urns out that ```client_sock.settimeout(0.1)``` is causing this error...

By removing this instruction, the weird OSError i no longer thrown but i kinda need to set a timeout when reading...

Any idea or workaround?
