### ISSUE TITLE
"python setup.py install" does not work on OSX (because lightaquablue)

### ISSUE THREAD

**Issue by rambo** [pybluez/pybluez#379]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** osx catalina
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) mbp
 - **Python Version:** 3.9
 - **PyBluez Version:** git d7f36702bba2abc8ea41977b2eea56a17431ac6d

## Issue

Found when debugging #378 

```
(pybluezdev) ➜  pybluez git:(issue-378) ✗ python setup.py install
running install
running bdist_egg
running egg_info
writing PyBluez.egg-info/PKG-INFO
writing dependency_links to PyBluez.egg-info/dependency_links.txt
writing eager_resources to PyBluez.egg-info/eager_resources.txt
writing requirements to PyBluez.egg-info/requires.txt
writing top-level names to PyBluez.egg-info/top_level.txt
reading manifest file 'PyBluez.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching '*.c' under directory 'macos'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '*.o' found under directory '*'
warning: no previously-included files matching '*.opp' found under directory '*'
writing manifest file 'PyBluez.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.15-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.15-x86_64/egg
creating build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/btcommon.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/ble.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/macos.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/__init__.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/bluez.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/msbt.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
copying build/lib/bluetooth/widcomm.py -> build/bdist.macosx-10.15-x86_64/egg/bluetooth
creating build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/PKG-INFO -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/eager_resources.txt -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/not-zip-safe -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/SOURCES.txt -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/requires.txt -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/top_level.txt -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
copying build/lib/PyBluez.egg-info/dependency_links.txt -> build/bdist.macosx-10.15-x86_64/egg/PyBluez.egg-info
creating build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_bluetoothsockets.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_LightAquaBlue.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_obexcommon.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_IOBluetoothUI.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/__init__.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_IOBluetooth.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
creating build/bdist.macosx-10.15-x86_64/egg/lightblue/__pycache__
copying build/lib/lightblue/__pycache__/__init__.cpython-39.pyc -> build/bdist.macosx-10.15-x86_64/egg/lightblue/__pycache__
copying build/lib/lightblue/__pycache__/_IOBluetooth.cpython-39.pyc -> build/bdist.macosx-10.15-x86_64/egg/lightblue/__pycache__
copying build/lib/lightblue/__pycache__/_LightAquaBlue.cpython-39.pyc -> build/bdist.macosx-10.15-x86_64/egg/lightblue/__pycache__
copying build/lib/lightblue/__pycache__/_lightblue.cpython-39.pyc -> build/bdist.macosx-10.15-x86_64/egg/lightblue/__pycache__
copying build/lib/lightblue/_obex.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_lightblue.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/obex.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_macutil.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
copying build/lib/lightblue/_lightbluecommon.py -> build/bdist.macosx-10.15-x86_64/egg/lightblue
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/btcommon.py to btcommon.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/ble.py to ble.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/macos.py to macos.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/bluez.py to bluez.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/msbt.py to msbt.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/bluetooth/widcomm.py to widcomm.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_bluetoothsockets.py to _bluetoothsockets.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_obexcommon.py to _obexcommon.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_IOBluetoothUI.py to _IOBluetoothUI.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_obex.py to _obex.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/obex.py to obex.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_macutil.py to _macutil.cpython-39.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/lightblue/_lightbluecommon.py to _lightbluecommon.cpython-39.pyc
creating build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/PKG-INFO -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/SOURCES.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/dependency_links.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/eager_resources.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/not-zip-safe -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/requires.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying PyBluez.egg-info/top_level.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
creating 'dist/PyBluez-0.30-py3.9.egg' and adding 'build/bdist.macosx-10.15-x86_64/egg' to it
removing 'build/bdist.macosx-10.15-x86_64/egg' (and everything under it)
Processing PyBluez-0.30-py3.9.egg
creating /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg
Extracting PyBluez-0.30-py3.9.egg to /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages
Adding PyBluez 0.30 to easy-install.pth file

Installed /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg
Processing dependencies for PyBluez==0.30
Searching for pyobjc-framework-Cocoa==7.1
Best match: pyobjc-framework-Cocoa 7.1
Adding pyobjc-framework-Cocoa 7.1 to easy-install.pth file

Using /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages
Searching for pyobjc-core==7.1
Best match: pyobjc-core 7.1
Adding pyobjc-core 7.1 to easy-install.pth file

Using /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages
Finished processing dependencies for PyBluez==0.30
(pybluezdev) ➜  pybluez git:(issue-378) ✗ python 
Python 3.9.1 (default, Dec 10 2020, 10:36:35) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluetooth
/Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/objc/_bridgesupport.py:13: UserWarning: Module lightblue was already imported from /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg/lightblue/__init__.py, but /Users/rambo/devel/pybluez is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rambo/devel/pybluez/bluetooth/__init__.py", line 38, in <module>
    from .macos import *
  File "/Users/rambo/devel/pybluez/bluetooth/macos.py", line 1, in <module>
    import lightblue
  File "/Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg/lightblue/__init__.py", line 160, in <module>
    from ._lightblue import *
  File "/Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg/lightblue/_lightblue.py", line 29, in <module>
    from . import _LightAquaBlue
  File "/Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg/lightblue/_LightAquaBlue.py", line 32, in <module>
    raise ImportError("Cannot load LightAquaBlue framework, not found at " + \
ImportError: Cannot load LightAquaBlue framework, not found at /Users/rambo/.virtualenvs/pybluezdev/lib/python3.9/site-packages/PyBluez-0.30-py3.9.egg/lightblue/LightAquaBlue.framework
>>> 
(pybluezdev) ➜  pybluez git:(issue-378) ✗ 
```

**Comment by hiwanz** [comment]
Operating System: osx bigsur
Hardware: (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) mbp
Python Version: 3.9

```

Building wheel for pybluez (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/setup.py'"'"'; __file__='"'"'/private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-wheel-1cebk0cr
       cwd: /private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/
  Complete output (16 lines):
  Command line invocation:
      /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild install -project macos/LightAquaBlue/LightAquaBlue.xcodeproj -scheme LightAquaBlue DSTROOT=/private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/macos INSTALL_PATH=/ DEPLOYMENT_LOCATION=YES
  
  Build settings from command line:
      DEPLOYMENT_LOCATION = YES
      DSTROOT = /private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/macos
      INSTALL_PATH = /
  
  xcodebuild: error: 'macos/LightAquaBlue/LightAquaBlue.xcodeproj' does not exist.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/setup.py", line 79, in <module>
      subprocess.check_call([
    File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['xcodebuild', 'install', '-project', 'macos/LightAquaBlue/LightAquaBlue.xcodeproj', '-scheme', 'LightAquaBlue', 'DSTROOT=/private/var/folders/47/sw37s42j6zg5wrcgzgj0qg3w0000gn/T/pip-install-eigv1zk3/pybluez_175419493d7b474cbf23dda13d9b812d/macos', 'INSTALL_PATH=/', 'DEPLOYMENT_LOCATION=YES']' returned non-zero exit status 66.
  ----------------------------------------
  ERROR: Failed building wheel for pybluez```

**Comment by RomanoB** [comment]
Same as @hiwanz here.

**Comment by TheFinalJoke** [comment]
Found what is wrong, The in the setup.py install LightAquaBlue builds a macos package using xcodebuild. While my testing, it is failing every-time. Hopefully will have a PR up soon 
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'xcodebuild', 'install', '-project', 'macos/LightAquaBlue/LightAquaBlue.xcodeproj', '-scheme', 'LightAquaBlue', 'DSTROOT=/Users/nickshorter/pybluez/macos', 'INSTALL_PATH=/', 'DEPLOYMENT_LOCATION=YES']' returned non-zero exit status 1.`

**Comment by rambo** [comment]
https://github.com/pybluez/pybluez/pull/381 should "solve" the compile issue, it doesn't seem to actually work though, something has changed in OSX APIs and lightaquablue was abandoned years ago
