### ISSUE TITLE
LightAquaBlue failing to compile on Apple Silicon

### ISSUE THREAD

**Issue by Animenosekai** [pybluez/pybluez#393]
## System

 - **Operating System:** macOS 11.2.3
 - **Hardware:** MacBook Air Internal Bluetooth (v. 8.0.3d9)
 - **Python Version:** Python 3.9.1 | packaged by conda-forge | (default, Dec  9 2020, 01:07:47) [Clang 11.0.0 ] on darwin
 - **PyBluez Version:** 0.30

## Issue

I tried to install PyBluez on my MacBook Air (2020, M1) but it seems to fail to compile LightAquaBlue.

I tried installing it from the current PyPI version, the current `master` version and other forks but nothing seems to work.

I also tried installing it from the source code and by compiling LightAquaBlue afterward but it still gives me this message when I try to import `bluetooth`:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/bluetooth/__init__.py", line 47, in <module>
    from .osx import *
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/bluetooth/osx.py", line 1, in <module>
    import lightblue
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/lightblue/__init__.py", line 160, in <module>
    from ._lightblue import *
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/lightblue/_lightblue.py", line 29, in <module>
    from . import _LightAquaBlue
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/lightblue/_LightAquaBlue.py", line 32, in <module>
    raise ImportError("Cannot load LightAquaBlue framework, not found at " + \
ImportError: Cannot load LightAquaBlue framework, not found at /Users/animenosekai/miniforge3/lib/python3.9/site-packages/lightblue/LightAquaBlue.framework
```

**Comment by sapkra** [comment]
Where you able to fix the problem somehow? I came across the same one.

**Comment by dhguswns23** [comment]
same here :(
