### ISSUE TITLE
Connection is not happening when i use pybluez in windows

### ISSUE THREAD

**Issue by PremkumarThotadi** [pybluez/pybluez#463]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** windows 10
 - **Hardware:** laptop internal bluetooth
 - **Python Version:** 3.7.5
 - **PyBluez Version:** 0.22

## Issue
i am able to find the bluetooth devices around me , but unable to connect and send files from laptop bluetooth to other devices like phone.

i am getting the following error:

![bluetooth error_pybluz](https://user-images.githubusercontent.com/105772018/209274647-7444e274-368e-42eb-8cb4-f4b5581b1ef5.PNG)

**Comment by lolPlatinumPlayer** [comment]
same problem. 
```cmd
Traceback (most recent call last):
  File "C:\add_by_user\work_project\lin_xian\first_iot\code\test_python_bluetooth2\play_music.py", line 23, in <module>
    play_music(music_file, device_address)
  File "C:\add_by_user\work_project\lin_xian\first_iot\code\test_python_bluetooth2\play_music.py", line 14, in play_music
    sock.send(chunk)
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\pybluez-0.30-py3.11-win-amd64.egg\bluetooth\msbt.py", line 102, in send
OSError: 你的主机中的软件中止了一个已建立的连接。
```
