### ISSUE TITLE
Not compatible with M1 MacBook?

### ISSUE THREAD

**Issue by slerman12** [pybluez/pybluez#469]
I installed pybluez and get this error when trying to import on an M1 MacBook:

```
import bluetooth
  File "/Users/samlerman/Code/miniforge3/lib/python3.9/site-packages/bluetooth/__init__.py", line 47, in <module>
    from .macos import *
  File "/Users/samlerman/Code/miniforge3/lib/python3.9/site-packages/bluetooth/macos.py", line 1, in <module>
    import lightblue
ModuleNotFoundError: No module named 'lightblue'
```

**Comment by medukonis** [comment]
Same issue on M2 MacBook Pro. MacOS Ventura

**Comment by zakutnya** [comment]
It's not about M1/2, it's about macOS. At least i just came up with the same `ModuleNotFoundError: No module named 'lightblue'` on Intel MacBook Pro.

The solution was incredibly simple:
```bash
pip install python-lightblue
```

Sadly, that hasn't helped me in general, eg.:
i use `bluetooth.lookup_name()` that perfectly does it's job on Linux, but just prints out `TODO: implement` on macOS 😐

**Comment by Alexandro1112** [comment]
I same working on Mac Book M1, and I installed pyobjc, and Bluetooth modules.

**Comment by vladRudenua23** [comment]
any updates ?

**Comment by jdcrunchman** [comment]
When will there be updates...
I still did:    pip install python-lightblue

I'm running on an M1 Mac.   I really need this working....  this is driving me crazy...

Here's the source code.......

import bluetooth

def discover_devices():
    print("Discovering nearby devices:")
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, lookup_class=True, flush_cache=True)
    
    for addr, name, _ in nearby_devices:
        print(f"Found device: {name} - {addr}")

if __name__ == "__main__":
    discover_devices()

When I run it,   I get:
(BLE_39_env) johndraper@Johns-MacBook-Pro MacPython % python3 Blu_discovery.py
Discovering nearby devices:
Traceback (most recent call last):
  File "/Volumes/T7/Programming/CrunchComm/MacPython/Blu_discovery.py", line 11, in <module>
    discover_devices()
  File "/Volumes/T7/Programming/CrunchComm/MacPython/Blu_discovery.py", line 5, in discover_devices
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, lookup_class=True, flush_cache=True)
  File "/Volumes/T7/Programming/CrunchComm/MacPython/BLE_39_env/lib/python3.9/site-packages/bluetooth/macos.py", line 12, in discover_devices
    devices = lightblue.finddevices(getnames=lookup_names, length=duration)
AttributeError: module 'lightblue' has no attribute 'finddevices'
(BLE_39_env) johndraper@Johns-MacBook-Pro MacPython % 

What am I doing wrong?     Please help!!!    I really need this....

**Comment by jdcrunchman** [comment]
Is there a workaround?

**Comment by jdcrunchman** [comment]
Yea,   if there is a published workaround,   where would I find it.   It's been about 5 days now,   I tried solving it,  but its way past my pay scale.    Is anyone else still working on this problem?
