### ISSUE TITLE
Compilation error on example rfcomm-server.py

### ISSUE THREAD

**Issue by AmberElferink** [pybluez/pybluez#478]
## System

 - **Operating System:** Windows 11
 - **Hardware:** Windows PC
 - **Python Version:** 3.7.3
 - **PyBluez Version:** pybluez2-0.46

## Issue

After `pip install pybluez2`, which is the only command that worked for me to install this on Windows (see other issue, if I run the example rfcomm-server.py script I get: 
```
Traceback (most recent call last):
  File "c:\CodeRepositories\bluetooth\PC\rfcomm-server.py", line 12, in <module>
    server_sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
  File "C:\Users\eempi\anaconda3\envs\CoralDevBoard\lib\site-packages\bluetooth\native_socket.py", line 16, in __init__
    _proto = protocols[proto]
KeyError: 3
```
Does anyone know how to fix this?

**Comment by quepas** [comment]
First of all, the source code of `pybluez2` package is hosted here: https://github.com/airgproducts/pybluez2. Regarding your problem, change `bluetooth.RFCOMM` to `Protocols.RFCOMM` like this:

```python
import bluetooth
from bluetooth import Protocols

server_sock = bluetooth.BluetoothSocket(Protocols.RFCOMM)
```
The reason why this helps is that the [BluetoothSocket](https://github.com/airgproducts/pybluez2/blob/master/bluetooth/native_socket.py) defines a dictionary of protocols based on keys from the [Protocols](https://github.com/airgproducts/pybluez2/blob/master/bluetooth/btcommon.py#L7) enumeration which holds a different value for `RFCOMM` than the global one:

https://github.com/airgproducts/pybluez2/blob/master/bluetooth/btcommon.py#L7C1-L14C9
```python
class Protocols(enum.Enum):
    L2CAP = 10
    RFCOMM = 11
    OBEX = 12

L2CAP=0
RFCOMM=3
```
