### ISSUE TITLE
server_socket.bind results in "SystemError: argument 2 (impossible<bad format char>)"

### ISSUE THREAD

**Issue by upidapi** [pybluez/pybluez#489]
## System

   - Operating System: win 10
   - Hardware: external Bluetooth adaptor
   - Python Version: 3.12
   - PyBluez Version: 0.30

## Issue

Traceback (most recent call last):
  File "C:\Users\videw\PycharmProjects\MacroLib\Pybluez\Mine.py", line 7, in <module>
    server_socket.bind(("", bluetooth.PORT_ANY))
  File "C:\Users\videw\PycharmProjects\MacroLib\venv\Lib\site-packages\bluetooth\msbt.py", line 84, in bind
    bt.bind (self._sockfd, addr, port)
SystemError: argument 2 (impossible<bad format char>)

## Code

import time

import bluetooth

server_socket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
server_socket.bind(("", bluetooth.PORT_ANY))
server_socket.listen(1)

client_socket, client_address = server_socket.accept()
print(f"Accepted connection from {client_address}")
data_received = client_socket.recv(1024)

time.sleep(10)

client_socket.close()
server_socket.close()

What am i doing wrong?

**Comment by ShouryaGoje** [comment]
The Code only Works with Pyhton 3.11. I've tried it with python 3.11.5 and it works properly
