### ISSUE TITLE
"Address family not supported" on Ubuntu 22.04

### ISSUE THREAD

**Issue by RealMW96** [pybluez/pybluez#497]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: WSL2 on Windows 11; Ubuntu 22.04 LTS**
 - **Python Version: 3.10 & 3.12**
 - **PyBluez Version: Latest**

## Issue

Hi,

when I intend to run the example "inquiry.py", it works perfectly fine on Windows 11 and I obtain all Bluetooth devices nearby. However, if I try the same in Ubuntu 22.04 inside WSL2 on Windows 11, I obtain the following error:
 

Traceback (most recent call last):
  File "/mnt/c/Users/main/Desktop/pybluez-master/pybluez-master/examples/simple/inquiry.py", line 15, in <module>
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/PyBluez-0.30-py3.12-linux-x86_64.egg/bluetooth/bluez.py", line 19, in discover_devices
OSError: [Errno 97] Address family not supported by protocol

Any ideas what might cause this issue and how to solve it?

**Comment by RealMW96** [comment]
I managed to solve it. WSL2 was causing errors at it uses a NAT-based networking architecture by default. However, turning the "mirrored" mode on (https://learn.microsoft.com/en-us/windows/wsl/networking) did not help. Instead, i run the code now directly on Ubuntu via dual boot. There, everything is fine regarding IP adresses.
